version: '3.4'

services:
  # proxy:
  #   image: registry.gitlab.com/mireu-lab/docker-ssh-conteiner:containernetwork
  #   restart: always
  #   container_name: Proxy-Container
  #   environment:
  #     - VIRTUAL_HOST=test2.container.mireu.xyz
  #     - ProxyURL="0.0.0.0"
  #     - WebProxyPort="8080"
  #   depends_on:
  #     - ubuntu_jupyter
  #     - fedora_jupyter

  debian_jupyter:
    image: registry.gitlab.com/mireu-lab/docker-jupyter-container:containerjupyterdebian
    restart: always
    container_name: Jupyter-Debian-Container
    volumes:
      - Container_Jupyter:/workspace
    ports:
      - "8080:8888"
    depends_on:
      - datebase_mongo
      - datebase_mariadb
      - datebase_mysql
      - schema_redis

  ubuntu_jupyter:
    image: registry.gitlab.com/mireu-lab/docker-jupyter-container:containerjupyterubuntu
    restart: always
    container_name: Jupyter-Ubuntu-Container
    volumes:
      - Container_Jupyter:/workspace
    ports:
      - "8081:8888"
    depends_on:
      - datebase_mongo
      - datebase_mariadb
      - datebase_mysql
      - schema_redis
  
  fedora_jupyter:
    image: registry.gitlab.com/mireu-lab/docker-jupyter-container:containerjupyterfedora
    restart: always
    container_name: Jupyter-Fedora-Container
    volumes:
      - Container_Jupyter:/workspace
    ports:
      - "8082:8888"
    depends_on:
      - datebase_mongo
      - datebase_mariadb
      - datebase_mysql
      - schema_redis

  datebase_mongo:
    image: mongo
    restart: always
    container_name: Jupyter-MongoDB
    volumes:
      - Container_Datebase_MongoDB:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Jupyter

  datebase_mariadb:
    image: mariadb
    restart: always
    container_name: Jupyter-MariaDB
    volumes:
      - Container_Datebase_MariaDB:/var/lib/maria
    environment:
      MARIADB_ROOT_PASSWORD: Jupyter

  datebase_mysql:
    image: mysql
    restart: always
    container_name: Jupyter-MySQL
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - Container_Datebase_MySQL:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Jupyter

  detebase_postgres:
    image: postgres
    restart: always
    container_name: Jupyter-PostgresDB
    volumes:
      - Container_Datebase_PostgresDB:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: Jupyter

  schema_redis:
    image: redis:alpine
    restart: always
    container_name: Jupyter-Redis
    command: redis-server --port 6379
    volumes:
      - Container_Schema_Redis:/data
    labels:
      - "name=redis"
      - "mode=standalone"

volumes:
  Container_Jupyter:
  Container_Datebase_MySQL:
  Container_Datebase_MariaDB:
  Container_Datebase_PostgresDB:
  Container_Datebase_MongoDB:
  Container_Schema_Redis:
